// <------------ USER ------------>

// DA AGGIUSTARE: - se posto un type diverso da quelli consentiti crasha, invece nella put funziona
//GET

GET  http://localhost:3001/api/suppliers

###

GET http://localhost:3001/api/users

###

// solo per testare DA TOGLIERE IN SEGUITO

GET http://localhost:3001/api/all
###

//POST

POST http://localhost:3001/api/newUser
Content-Type: application/json

{
    "username":"user14@ezwh.com",
    "name":"Pippo",
    "surname" : "Pelle",
    "password" : "ciao1234",
    "type" : "pluto"

}

###

POST http://localhost:3001/api/managerSessions
Content-Type: application/json

{
    "credentials" : {

        "username" : "user2@ezwh.com",
        "password" : "testpassword" 
    }
}

###

POST http://localhost:3001/api/customerSessions
Content-Type: application/json

{
    "credentials" : {
        
        "username" : "user7@ezwh.com",
        "password" : "ciao" 
    }
}

###

POST http://localhost:3001/api/supplierSessions
Content-Type: application/json

{
    "credentials" : {
        
        "username" : "user7@ezwh.com",
        "password" : "ciao" 
    }
}

###

POST http://localhost:3001/api/clerkSessions
Content-Type: application/json

{
    "credentials" : {
        
        "username" : "user9@ezwh.com",
        "password" : "ciao" 
    }
}

###

POST http://localhost:3001/api/qualityEmployeeSessions
Content-Type: application/json

{
    "credentials" : {
        
        "username" : "user9@ezwh.com",
        "password" : "ciao" 
    }
}

###

POST http://localhost:3001/api/deliveryEmployeeSessions
Content-Type: application/json

{
    "credentials" : {
        
        "username" : "user11@ezwh.com",
        "password" : "ciao" 
    }
}

###

// PUT

PUT  http://localhost:3001/api/users/user10@ezwh.com
Content-Type: application/json

{
    "oldType" : "qualityEmployee",
    "newType" : "clerk"
}

###

// DELETE

DELETE http://localhost:3001/api/users/user1@ezwh.com/manager

###

