// <------------ RESTOCK ORDER ------------>

//GET

GET  http://localhost:3001/api/restockOrders

###

GET  http://localhost:3001/api/restockOrdersIssued

###

GET  http://localhost:3001/api/restockOrders/4

###

GET  http://localhost:3001/api/restockOrders/3/returnItems

###

//POST

POST http://localhost:3001/api/restockOrder
Content-Type: application/json

{
    "issueDate":"2025/11/29 15:33",
    "products": [{"SKUId":18,"description":"a product","price":21.99,"qty":15},
                {"SKUId":34,"description":"another product","price":11.99,"qty":20}],
    "supplierId" : 2
}

###

//PUT 

PUT http://localhost:3001/api/restockOrder/3
Content-Type: application/json

{
    "newState":"COMPLETEDRETURN"
}

###

PUT http://localhost:3001/api/restockOrder/1/skuItems
Content-Type: application/json

{
    "skuItems" : [{"SKUId":25,"rfid":"12345678901234567890123456789019"}]
}

###

PUT http://localhost:3001/api/restockOrder/3/transportNote
Content-Type: application/json

{
    "transportNote":{"deliveryDate":"2022/12/29"}
}

###

// DELETE
DELETE  http://localhost:3001/api/restockOrder/2

###

// <------------ RETURN ORDER ------------>

//GET

GET  http://localhost:3001/api/returnOrders

###

GET  http://localhost:3001/api/returnOrders/1

###

//POST

POST   http://localhost:3001/api/returnOrder
Content-Type: application/json

{
    "returnDate":"2022/11/19 10:30",
    "products": [{"SKUId":15,"description":"a product","price":25.99,"RFID":"12345678901234567890123456789018"},
                {"SKUId":34,"description":"another product","price":38.99,"RFID":"12345678901234567890123456789039"}],
    "restockOrderId" : 1
}

###

//DELETE

DELETE   http://localhost:3001/api/returnOrder/2

###

// <------------ INTERNAL ORDER ------------>

//GET

GET  http://localhost:3001/api/internalOrders

###

GET  http://localhost:3001/api/internalOrdersIssued

###

GET  http://localhost:3001/api/internalOrdersAccepted

###

GET  http://localhost:3001/api/internalOrders/3

###

//POST

POST   http://localhost:3001/api/internalOrders
Content-Type: application/json

{
    "issueDate":"2019/11/29 16:33",
    "products": [{"SKUId":100,"description":"a product","price":10.99,"qty":3},
                {"SKUId":103,"description":"another product","price":11.99,"qty":3}],
    "customerId" : 1
}

###

//PUT

PUT   http://localhost:3001/api/internalOrders/1
Content-Type: application/json

{
    "newState":"ACCEPTED"
}
###

PUT   http://localhost:3001/api/internalOrders/2
Content-Type: application/json

{
    "newState":"COMPLETED",
    "products":[{"SkuID":1,"RFID":"12345678901234567890123456789016"},{"SkuID":70,"RFID":"12345678901234567890123456789038"}]
}

###

// DELETE

DELETE   http://localhost:3001/api/internalOrders/1

###


